
# resume information
resume-index = 8408
seed = 3810360880929096405
rate = 1000      
shard = 1/1
nocapture = servername


adapter-ip = 10.10.13.48
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 1-65000
range = 10.129.199.98

